name: 'Ollama GitHub Code Reviewer'
description: 'Perform code review using Ollama API'
inputs:
  model:
    description: 'Ollama model to use for code review'
    required: true
    default: 'codellama'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      run: |
        echo "::set-output name=all_changed_files::src/core/branch-helper.ts src/core/input-helper.ts"
      shell: bash

    - name: Review code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        curl -sS https://webi.sh/gh | sh
        export PATH="$HOME/.local/bin:$PATH"

        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        
        function ollamaServe {
          echo "start ollama as serve mode begin"
          ollama serve
          echo "start ollama as serve mode finish"
        }

        ollamaServe &
        sleep 3

        echo "start to pull model:llama3"
        ollama --version
        ollama pull llama3
        ollama list
        
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          content=$(cat "$file")
          review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3", "prompt": "Review the following file:\n\n```\n'"$content"'\n```", "stream": false}' | jq -r '.response')
          comment="Ollama Code Review for \`$file\`:\n\n$review"
          echo "$comment" >> ollama_review.txt
        done

        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
      shell: bash
